import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { NgxSpinnerModule } from 'ngx-spinner';
import { AgmCoreModule } from '@agm/core';

import { OverlayContainer, Overlay } from '@angular/cdk/overlay';
import { MAT_MENU_SCROLL_STRATEGY } from '@angular/material/menu';
import { CustomOverlayContainer } from '@src/app/theme/utils/custom-overlay-container';
import { menuScrollStrategy } from '@src/app/theme/utils/scroll-strategy';

import { SharedModule } from '@src/app/shared/shared.module';
import { AppRoutingModule } from '@src/app/app.routing';
import { AppComponent } from '@src/app/app.component';
import { PagesComponent } from '@src/app/pages/pages.component';
import { NotFoundComponent } from '@src/app/pages/not-found/not-found.component';
import { TopMenuComponent } from '@src/app/theme/components/top-menu/top-menu.component';
import { MenuComponent } from '@src/app/theme/components/menu/menu.component';
import { SidenavMenuComponent } from '@src/app/theme/components/sidenav-menu/sidenav-menu.component';
import { BreadcrumbComponent } from '@src/app/theme/components/breadcrumb/breadcrumb.component';

import { AppSettings } from '@src/app/app.settings';
import { AppService } from '@src/app/app.service';
import { AppInterceptor } from '@src/app/theme/utils/app-interceptor';
import { OptionsComponent } from '@src/app/theme/components/options/options.component';
import { FooterComponent } from '@src/app/theme/components/footer/footer.component';
import { AutoGeneratedComponent } from '@src/app/auto-generated/auto-generated.component';


@NgModule({
   imports: [
    BrowserModule,
    BrowserAnimationsModule,
    HttpClientModule,
    NgxSpinnerModule,
    AgmCoreModule.forRoot({
      apiKey: 'AIzaSyA1rF9bttCxRmsNdZYjW7FzIoyrul5jb-s'
    }),
    SharedModule,
    AppRoutingModule
  ],
  declarations: [
    AppComponent,
    PagesComponent,
    NotFoundComponent,
    TopMenuComponent,
    MenuComponent,
    SidenavMenuComponent,
    BreadcrumbComponent,
    OptionsComponent,
    FooterComponent,
    AutoGeneratedComponent    
  ], 
  providers: [
    AppSettings,
    AppService,   
    { provide: OverlayContainer, useClass: CustomOverlayContainer },
    { provide: MAT_MENU_SCROLL_STRATEGY, useFactory: menuScrollStrategy, deps: [Overlay] },
    { provide: HTTP_INTERCEPTORS, useClass: AppInterceptor, multi: true }
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }